import { Geist, Mulish } from "next/font/google";
import { GoogleAnalytics } from '@next/third-parties/google'
 import { GoogleTagManager } from '@next/third-parties/google'

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import TimerSection from "@/components/LandingPage2/TimerSection";
import ElevenLabsAgent from "@/components/new/ElevenLabsAgent";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
  display: 'swap',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   const targetDate = '2025-07-31T23:59:59';
  return (
    <html lang="en">
       <GoogleTagManager gtmId="GTM-MVN6NVR" />
      <body
        className={`${geistSans.variable} ${mulish.className} antialiased`}
      >
        <Navbar />
        {children}
        <Footer/>
        <ElevenLabsAgent />
        <GoogleAnalytics gaId="G-YTTTXDKSTX" />
          <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-946516554"
          strategy="afterInteractive"
        />

        <Script id="google-ads" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-946516554');
          `}
        </Script>
      </body>
    </html>
  );
}
